import type { Plugin, PluginBuildContext } from "../core/plugins.ts";
import type {
  BuildResult,
  Collection,
  Config,
  PaginatedContent,
} from "../types/index.ts";
import { CollectionManager } from "../core/collections.ts";

export interface PaginationOptions {
  collections?: string[];
  perPage?: number;
  template?: string;
  indexPath?: string;
  pagePath?: string;
}

export function createPaginationPlugin(
  options: PaginationOptions = {},
): Plugin {
  const {
    collections = ["blog", "posts"],
    perPage = 10,
    template = "pagination",
    indexPath = "{collection}/index.html",
    pagePath = "{collection}/page/{page}/index.html",
  } = options;

  return {
    name: "pagination",
    version: "1.0.0",
    description: "Generate paginated collection pages",

    async afterBuild(context: PluginBuildContext & { result: BuildResult }) {
      const { config, files, result } = context;

      if (!result.success) {
        return;
      }

      const collectionManager = new CollectionManager(config);
      const allCollections = collectionManager.processCollections(files);

      // Filter collections that need pagination
      const paginatedCollections = allCollections.filter((collection) =>
        collections.includes(collection.name) &&
        collection.config.paginate !== false &&
        collection.files.length > perPage
      );

      if (paginatedCollections.length === 0) {
        console.log("📄 No collections require pagination");
        return;
      }

      let totalGenerated = 0;

      for (const collection of paginatedCollections) {
        const totalPages = Math.ceil(collection.files.length / perPage);

        // Generate paginated pages
        for (let page = 1; page <= totalPages; page++) {
          const paginatedContent = collectionManager.paginateCollection(
            collection,
            page,
          );

          // Determine output path
          let outputPath: string;
          if (page === 1) {
            outputPath = indexPath.replace("{collection}", collection.name);
          } else {
            outputPath = pagePath
              .replace("{collection}", collection.name)
              .replace("{page}", page.toString());
          }

          // Generate HTML for this page
          const html = await generatePaginationHtml(
            paginatedContent,
            collection,
            page,
            totalPages,
            config,
            template,
          );

          // Write file
          const fullPath = `${config.outputDir}/${outputPath}`;
          await Deno.mkdir(fullPath.split("/").slice(0, -1).join("/"), {
            recursive: true,
          });
          await Deno.writeTextFile(fullPath, html);

          totalGenerated++;
        }

        console.log(
          `📄 Generated ${totalPages} pages for ${collection.name} collection`,
        );
      }

      console.log(`📄 Generated ${totalGenerated} paginated pages total`);
    },
  };
}

function generatePaginationHtml(
  paginatedContent: PaginatedContent,
  collection: Collection,
  currentPage: number,
  totalPages: number,
  config: Config,
  _templateName: string,
): string {
  // This would typically use the template system
  // For now, generate a basic HTML structure
  const { files, hasNextPage, hasPrevPage, nextPagePath, prevPagePath } =
    paginatedContent;

  const items = files.map((file) => `
    <article class="post">
      <h2><a href="/${file.slug}.html">${
    file.frontMatter.title || file.slug
  }</a></h2>
      <p class="meta">${file.frontMatter.date || ""}</p>
      ${
    file.frontMatter.description
      ? `<p class="description">${file.frontMatter.description}</p>`
      : ""
  }
      ${
    file.frontMatter.tags
      ? `
        <div class="tags">
          ${
        (Array.isArray(file.frontMatter.tags)
          ? file.frontMatter.tags
          : [file.frontMatter.tags]).map((tag) =>
            `<span class="tag">${tag}</span>`
          ).join("")
      }
        </div>
      `
      : ""
  }
    </article>
  `).join("");

  const pagination = `
    <nav class="pagination">
      ${
    hasPrevPage ? `<a href="/${prevPagePath}" class="prev">← Previous</a>` : ""
  }
      <span class="page-info">Page ${currentPage} of ${totalPages}</span>
      ${hasNextPage ? `<a href="/${nextPagePath}" class="next">Next →</a>` : ""}
    </nav>
  `;

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${collection.name} - Page ${currentPage}</title>
</head>
<body>
  <header>
    <h1>${collection.name}</h1>
  </header>
  
  <main>
    ${items}
    ${pagination}
  </main>
  
  <footer>
    <p>Generated by Rig Static Site Generator</p>
  </footer>
</body>
</html>
  `.trim();
}

// Export a default plugin instance
export const paginationPlugin = createPaginationPlugin();
